version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5075:5075"
    volumes:
      - ../weights:/app/weights
      - ../rec_imdb.ann:/app/rec_imdb.ann
      - ../movies_metadata.csv:/app/movies_metadata.csv
    command: ["python", "movieposter_api.py", "--model_path", "weights/movieposter_net.pth"]

  gradio:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    ports:
      - "7860:7860"
    environment:
      - API_URL=http://api:5075/predict
    depends_on:
      - api