FROM python:3.10-slim

WORKDIR /app

# Installation des dépendances système pour les images
RUN apt-get update && apt-get install -y \
    libjpeg-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*


COPY requirements-gradio.txt .


RUN pip install --no-cache-dir -r requirements-gradio.txt


COPY app_gradio.py .

ENV GRADIO_ANALYTICS_ENABLED=False
EXPOSE 7860

CMD ["python", "app_gradio.py"]