version: '3.8'
services:
  annoy:
    build:
      context: .
      dockerfile: Dockerfile.annoy 
    ports:
      - "5000:5000"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5075:5075"
    command: ["python", "movieposter_api.py", "--model_path", "weights/movieposter_net.pth"]
    
  gradio:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    ports:
      - "7860:7860"
    environment:
      - API_URL=http://api:5075/predict
      - ANNOY_URL=http://annoy:5000/recommend
    depends_on:
      - api
      - annoy