version: '3.8'
services:
  annoy:
    build:
      context: .
      dockerfile: Dockerfile.annoy 
    ports:
      - "5000:5000"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5075:5075"
    command: ["python", "movieposter_api.py", "--model_path", "weights/movieposter_net.pth"]
    volumes:
      - torch_cache:/root/.cache/torch

  api_reco:
    build:
      context: .
      dockerfile: Dockerfile.api        # même image, commande différente
    ports:
      - "5076:5076"
    command: ["python", "movie_plot_api.py"]
    volumes:
      - huggingface_cache:/root/.cache/huggingface  
      - torch_cache:/root/.cache/torch
    depends_on:
      - api                             # api_reco démarre après api (même build)
  
  gradio:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    ports:
      - "7860:7860"
    environment:
      -  API_CLASSIFICATION_URL=http://api:5075/predict    #  onglet 1
      - API_RECOMMENDATION_URL=http://api_reco:5076/recommend  # onglet 2
      - ANNOY_URL=http://annoy:5000/recommend             # onglet 1
    depends_on:
      - api
      - api_reco
      - annoy


volumes:
  huggingface_cache:  
  torch_cache:


